name: blue_screen_example
description: An example of how to use blue_screen package with Flutter.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  blue_screen:
    path: ../../blue_screen

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Chs
      fonts:
        - asset: packages/blue_screen/fonts/chs_boot.ttf
    - family: Cht
      fonts:
        - asset: packages/blue_screen/fonts/cht_boot.ttf
    - family: Jpn
      fonts:
        - asset: packages/blue_screen/fonts/jpn_boot.ttf
    - family: Kor
      fonts:
        - asset: packages/blue_screen/fonts/kor_boot.ttf
    - family: Malgun
      fonts:
        - asset: packages/blue_screen/fonts/malgun_boot.ttf
    - family: Malgunn
      fonts:
        - asset: packages/blue_screen/fonts/malgunn_boot.ttf
    - family: Meiryo
      fonts:
        - asset: packages/blue_screen/fonts/meiryo_boot.ttf
    - family: Meiryon
      fonts:
        - asset: packages/blue_screen/fonts/meiryon_boot.ttf
    - family: Msjh
      fonts:
        - asset: packages/blue_screen/fonts/msjh_boot.ttf
    - family: Msjhn
      fonts:
        - asset: packages/blue_screen/fonts/msjhn_boot.ttf
    - family: Msyh
      fonts:
        - asset: packages/blue_screen/fonts/msyh_boot.ttf
    - family: Msyhn
      fonts:
        - asset: packages/blue_screen/fonts/msyhn_boot.ttf
    - family: Segmono
      fonts:
        - asset: packages/blue_screen/fonts/segmono_boot.ttf
    - family: Segoe
      fonts:
        - asset: packages/blue_screen/fonts/segoe_slboot.ttf
    - family: Segoen
      fonts:
        - asset: packages/blue_screen/fonts/segoen_slboot.ttf
    - family: Wgl4
      fonts:
        - asset: packages/blue_screen/fonts/wgl4_boot.ttf

